/**
 * XXX TODO
 */
[NoInterfaceObject]
interface Contact {
    /* singular fields */

    //XXX philikon: I don't think it's very useful to declare 'id' to be
    // readonly, unless we give contact syncing apps a way to associate
    // their upstream IDs with the contact as well and query by it.
    readonly attribute DOMString              id;
    readonly attribute Date?                  published;
    readonly attribute Date?                  updated;

             attribute DOMString?             displayName;
             attribute ContactName?           name;
             attribute DOMString?             nickname;
             attribute DOMString?             note;
             attribute Date?                  birthday;

    /* plural fields */

             attribute ContactField[]?        emails;
             attribute ContactField[]?        urls;
             attribute ContactField[]?        phoneNumbers;
             attribute ContactField[]?        ims;
             attribute ContactField[]?        photos;
             attribute ContactAddress[]?      addresses;
             attribute ContactOrganization[]? organizations;
             attribute DOMString[]?           categories; // PoCo calls these tags?

    //TODO additional PoCo fields?
};


/**
 * XXX TODO
 * 
 * (This is similar to the W3C API, though it also includes the 'formatted'
 * field as defined by PoCo and allows multiple values for name segments
 * as defined by vCard4.)
 */
[NoInterfaceObject]
interface ContactName {
    attribute DOMString? formatted;
    attribute DOMString[]? familyName;
    attribute DOMString[]? givenName;
    attribute DOMString[]? middleName;
    attribute DOMString[]? honorificPrefix;
    attribute DOMString[]? honorificSuffix;
};

/**
 * XXX TODO
 * 
 * (This is similar to the W3C API, though it uses 'primary' instead of
 * 'pref'.)
 */
[NoInterfaceObject]
interface ContactField {
    attribute boolean    primary;
    attribute DOMString  type;
    attribute DOMString? value;
};


/**
 * XXX TODO
 * 
 * (This is similar to the W3C API, though it uses 'primary' instead of
 * 'pref' and adds the 'formatted' attribute as defined by PoCo.)
 */
[NoInterfaceObject]
interface ContactAddress {
    attribute boolean    primary;
    attribute DOMString  type;
    attribute DOMString? formatted;
    attribute DOMString? streetAddress;
    attribute DOMString? locality;
    attribute DOMString? region;
    attribute DOMString? postalCode;
    attribute DOMString? country;
};

/**
 * XXX TODO
 * 
 * (This is similar to the W3C API, though it uses 'primary' instead of
 * 'pref' and XXX TODO.)
 */
[NoInterfaceObject]
interface ContactOrganization {
    attribute boolean    primary;
    attribute DOMString  type;
    attribute DOMString? name;
    attribute DOMString? department;
    attribute DOMString? title;
    //XXX TODO additional PoCo fields?
};
